apiVersion: v1
kind: Service
metadata:
  name: mongodb-order-management-service
  namespace: ecommerce
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP    
  selector:
    app: mongodb-order-management