apiVersion: v1
kind: Service
metadata:
  name: order-management-service
  namespace: ecommerce
  labels:
    app: order-management
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: order-management
  