apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
  namespace: ecommerce
  labels:
    app: order-management
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
      - name: order-management
        image: hema995/e-commerce-app-main_order:v1.0.0
        ports:
        - containerPort: 9090
        envFrom:
          - configMapRef:
              name: order-management-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m" 
        
      
