apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-customer-support
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: customer-support
    app.kubernetes.io/part-of: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: customer-support
  template:
    metadata:
      labels:
        app.kubernetes.io/name: customer-support
        app.kubernetes.io/part-of: ecommerce
    spec:
      initContainers:
        - name: init-mongodb
          image: mongo:4.4.6
          command: ['sh', '-c', 'until nc -z mongodb-contact-support 27017; do echo waiting for mongodb; sleep 2; done;']
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      containers:
        - name: customer-support
          image: hema995/e-commerce-app-main_contact-support:v1.0.0
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /api/contact-messages
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /api/contact-messages
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: customer-support-config
            - secretRef:
                name: mongodb-secret
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true