apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-support-config
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: customer-support
    app.kubernetes.io/part-of: ecommerce
data:
  MONGODB_HOST: mongo-contact-support-service
  MONGODB_PORT: "27017"
