apiVersion: v1
kind: Service
metadata:
  name: contact-support-service
  namespace: ecommerce
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: customer-support