apiVersion: v1
kind: Service
metadata:
  name: mongo-contact-support-service
  namespace: ecommerce
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP
  labels:
    app: mongodb-contact-support    
  selector:
    app: mongodb-contact-support