apiVersion: v1
kind: Service
metadata:
  name: mongo-contact-support-service
  namespace: ecommerce
  labels:                       # ✅ Correct location
    app: mongodb-contact-support
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP
  selector:
    app: mongodb-contact-support