apiVersion: v1
kind: Service
metadata:
  name: product-inventory-service
  namespace: ecommerce
spec:
  type: LoadBalancer
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app.kubernetes.io/name: product-inventory