
        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: product-inventory
    app.kubernetes.io/part-of: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: product-inventory
  template:
    metadata:
      labels:
        app.kubernetes.io/name: product-inventory
        app.kubernetes.io/part-of: ecommerce
    spec:
      containers:
        - name: product-inventory
          image: hema995/e-commerce-app-main_inventory:v1.0.0
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: product-inventory-config
            - secretRef:
                name: postgres-product-inventory-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
