apiVersion: v1
kind: Service
metadata:
  name: product-inventory-service
  namespace: ecommerce
  labels:
    app: product-inventory
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: product-inventory