apiVersion: v1
kind: Service
metadata:
  name: postgres-product-inventory
  namespace: ecommerce
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-product-inventory