apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-product-inventory
  namespace: ecommerce
  labels:
    app: postgres-product-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product-inventory
  template:
    metadata:
      labels:
        app: postgres-product-inventory
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-product-inventory-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-product-inventory-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-product-inventory-secret
                  key: POSTGRES_DB
            - name: PGDATA
              value: /mnt/data/pgdata      
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /mnt/data
              name: postgres-product-inventory-pvc
      volumes:
        - name: postgres-product-inventory-pvc
          persistentVolumeClaim:
            claimName: postgres-product-inventory-pvc