apiVersion: v1
kind: Secret
metadata:
  name: product-inventory-secret
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_DB: inventory-db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  