apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-profile-management
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: mysql-profile-management
    app.kubernetes.io/part-of: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-profile-management
  template:
    metadata:
      labels:
        app: mysql-profile-management
    spec:
      
      containers:
        - name: mysql-profile-management
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: profile-management-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: profile-management-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-management-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-management-secret
                  key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: mysql-profile-management-pvc
              mountPath: /mnt/data
      volumes:
        - name: mysql-profile-management-pvc
          persistentVolumeClaim:
            claimName: mysql-profile-management-pvc