apiVersion: v1
kind: Service
metadata:
  name: mysql-profile-svc
  namespace: ecommerce
  labels:
    app: mysql-profile-svc
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: ClusterIP
  selector:
    app: mysql-profile-management