apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-profile-management-pvc
  namespace: ecommerce
spec:
  resources:
    requests:
      storage: 3Gi
    limits:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo