apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-management
  namespace: ecommerce
  labels:
    app: profile-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-management
  template:
    metadata:
      labels:
        app: profile-management
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup mysql-profile-management; do echo waiting for myservice; sleep 2; done;']
      containers:
        - name: profile-management
          image: hema995/e-commerce-app-main_profile-management:v1.0.0
          ports:
            - containerPort: 3003
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: profile-management-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: profile-management-config
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: profile-management-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: profile-management-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-management-secret
                  key: MYSQL_PASSWORD
          
                  