apiVersion: v1
kind: Service
metadata:
  name: profile-management-service
  namespace: ecommerce 
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
  selector:
    app: profile-management
