apiVersion: v1
kind: Service
metadata: 
  name: profile-management
  namespace: ecommerce 
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3003
      targetPort: 3003
      protocol: TCP
  selector:
    app : profile-management