apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-profile-management-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard