apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-and-handling
  labels:
    app: shipping-and-handling
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-and-handling
  template:
    metadata:
      labels:
        app: shipping-and-handling
    spec:
      containers:
        - name: shipping-and-handling
          image: hema995/e-commerce-app-main_shipping:v1.0.0
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: shipping-handling-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m" 
          
          