apiVersion: v1
kind: Service
metadata:
  name: "product-catalog-service"
  labels:
    app: product-catalog
    service: product-catalog
  namespace: ecommerce
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: product-catalog
