apiVersion: v1
kind: ConfigMap
metadata:
  name: product-catalog-config
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: product-catalog
    app.kubernetes.io/part-of: ecommerce
data:
  MONGODB_HOST: mongo-product-catalog-service
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: product-catalog
