apiVersion: v1
kind: Service
metadata:
  name: mongo-product-catalog-service
  namespace: ecommerce
  labels:
    app: mongodb-product-catalog  # ✅ Correct placement
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP
  selector:
    app: mongodb-product-catalog