apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ui
  namespace: ecommerce
  labels:
    app: ecommerce-ui
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app.kubernetes.io/name: ecommerce-ui
